# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: COS 597S: Advanced Topics in Computer Science-Recent Advances in Wireless Networks
email: kyle.jamieson@princeton.edu
description: >- # this means to ignore newlines until "baseurl:"
  This graduate seminar will explore selected topics in wireless networks drawn from the 
  recent research literature and industry. The approach is interdisciplinary and 
  cross-layer, covering applications and end-to-end transport protocols, as well as 
  physical- and link-layer design, aiming to gain an understanding of how their 
  interactions influence performance. Areas of interest will include machine 
  learning-based wireless channel modeling, 5G and Open RAN network architecture, 
  computational structures for physical-layer processing, millimeter-wave reconfigurable 
  intelligent surfaces, and congestion control/queue management.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  kyleatprinceton

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
